import type { Customer, Order, Subscription } from "./types";

export const CUSTOMERS: Customer[] = [
  {
    id: "c1",
    name: "田中 太郎",
    email: "tanaka.taro@example.com",
    since: "2025-11-03",
    purchases: 3,
    spent: 7400,
    phone: "+8190-1234-5678",
    hasActiveSubscription: false,
    tags: [],
  },
  {
    id: "c2",
    name: "佐藤 花子",
    email: "sato.hanako@example.com",
    since: "2025-12-15",
    purchases: 1,
    spent: 1200,
    hasActiveSubscription: false,
    tags: [],
  },
  {
    id: "c3",
    name: "鈴木 一郎",
    email: "suzuki.ichiro@example.com",
    since: "2026-01-08",
    purchases: 5,
    spent: 21400,
    phone: "+8180-9876-5432",
    hasActiveSubscription: true,
    tags: ["VIP"],
  },
  {
    id: "c4",
    name: "山田 美咲",
    email: "yamada.misaki@example.com",
    since: "2026-01-22",
    purchases: 2,
    spent: 4000,
    hasActiveSubscription: false,
    tags: [],
  },
  {
    id: "c5",
    name: "中村 健太",
    email: "nakamura.kenta@example.com",
    since: "2026-02-10",
    purchases: 4,
    spent: 14800,
    hasActiveSubscription: true,
    tags: [],
  },
  {
    id: "c6",
    name: "伊藤 さくら",
    email: "ito.sakura@example.com",
    since: "2026-02-28",
    purchases: 1,
    spent: 980,
    hasActiveSubscription: false,
    tags: [],
  },
  {
    id: "c7",
    name: "渡辺 大輔",
    email: "watanabe.daisuke@example.com",
    since: "2026-03-05",
    purchases: 2,
    spent: 3200,
    phone: "+8170-1111-2222",
    hasActiveSubscription: false,
    tags: [],
  },
  {
    id: "c8",
    name: "小林 あかり",
    email: "kobayashi.akari@example.com",
    since: "2026-03-19",
    purchases: 7,
    spent: 38600,
    hasActiveSubscription: true,
    tags: ["VIP"],
  },
  {
    id: "c9",
    name: "加藤 浩二",
    email: "kato.koji@example.com",
    since: "2026-04-01",
    purchases: 1,
    spent: 1500,
    hasActiveSubscription: false,
    tags: [],
  },
  {
    id: "c10",
    name: "吉田 真由",
    email: "yoshida.mayu@example.com",
    since: "2026-04-14",
    purchases: 3,
    spent: 9800,
    hasActiveSubscription: true,
    tags: [],
  },
  {
    id: "c11",
    name: "松本 翔",
    email: "matsumoto.sho@example.com",
    since: "2026-05-02",
    purchases: 1,
    spent: 800,
    hasActiveSubscription: false,
    tags: [],
  },
  {
    id: "c12",
    name: "井上 奈々",
    email: "inoue.nana@example.com",
    since: "2026-05-20",
    purchases: 2,
    spent: 2700,
    hasActiveSubscription: false,
    tags: [],
  },
];

export const ORDERS: Order[] = [
  { id: "o1",  customerId: "c1",  productId: "9",  productName: "サラダの教科書",         amount: 1400,  status: "completed",        orderedAt: "2026-03-10" },
  { id: "o2",  customerId: "c1",  productId: "4",  productName: "朝食レシピ30",           amount: 800,   status: "completed",        orderedAt: "2026-04-22" },
  { id: "o3",  customerId: "c1",  productId: "6",  productName: "だしの基本ガイドブック",   amount: 3000,  status: "refunded",         orderedAt: "2026-05-01" },
  { id: "o4",  customerId: "c2",  productId: "1",  productName: "やさしい料理の基本",      amount: 1200,  status: "completed",        orderedAt: "2026-01-15" },
  { id: "o5",  customerId: "c3",  productId: "8",  productName: "パスタの基礎 動画講座",   amount: 6800,  status: "completed",        orderedAt: "2025-12-01" },
  { id: "o6",  customerId: "c3",  productId: "2",  productName: "旬の野菜 動画レッスン全30本", amount: 9800, status: "completed",     orderedAt: "2026-01-05" },
  { id: "o7",  customerId: "c3",  productId: "9",  productName: "サラダの教科書",         amount: 1400,  status: "completed",        orderedAt: "2026-02-14" },
  { id: "o8",  customerId: "c3",  productId: "4",  productName: "朝食レシピ30",           amount: 800,   status: "completed",        orderedAt: "2026-03-20" },
  { id: "o9",  customerId: "c3",  productId: "11", productName: "ふわふわパンケーキの科学", amount: 1100,  status: "completed",        orderedAt: "2026-05-10" },
  { id: "o10", customerId: "c4",  productId: "5",  productName: "献立テンプレ30日分",      amount: 1500,  status: "completed",        orderedAt: "2026-02-01" },
  { id: "o11", customerId: "c4",  productId: "7",  productName: "鮭の作り置きレシピ",      amount: 980,   status: "awaiting_payment", orderedAt: "2026-06-20" },
  { id: "o12", customerId: "c5",  productId: "8",  productName: "パスタの基礎 動画講座",   amount: 6800,  status: "completed",        orderedAt: "2025-11-20" },
  { id: "o13", customerId: "c5",  productId: "2",  productName: "旬の野菜 動画レッスン全30本", amount: 9800, status: "completed",     orderedAt: "2025-12-15" },
  { id: "o14", customerId: "c5",  productId: "9",  productName: "サラダの教科書",         amount: 1400,  status: "completed",        orderedAt: "2026-01-08" },
  { id: "o15", customerId: "c5",  productId: "4",  productName: "朝食レシピ30",           amount: 800,   status: "refunded",         orderedAt: "2026-02-10" },
  { id: "o16", customerId: "c6",  productId: "1",  productName: "やさしい料理の基本",      amount: 980,   status: "completed",        orderedAt: "2026-03-05" },
  { id: "o17", customerId: "c7",  productId: "5",  productName: "献立テンプレ30日分",      amount: 1500,  status: "completed",        orderedAt: "2026-04-10" },
  { id: "o18", customerId: "c7",  productId: "7",  productName: "鮭の作り置きレシピ",      amount: 980,   status: "completed",        orderedAt: "2026-05-15" },
  { id: "o19", customerId: "c8",  productId: "8",  productName: "パスタの基礎 動画講座",   amount: 6800,  status: "completed",        orderedAt: "2025-10-01" },
  { id: "o20", customerId: "c8",  productId: "2",  productName: "旬の野菜 動画レッスン全30本", amount: 9800, status: "completed",     orderedAt: "2025-11-10" },
  { id: "o21", customerId: "c8",  productId: "9",  productName: "サラダの教科書",         amount: 1400,  status: "completed",        orderedAt: "2025-12-20" },
  { id: "o22", customerId: "c8",  productId: "4",  productName: "朝食レシピ30",           amount: 800,   status: "completed",        orderedAt: "2026-01-15" },
  { id: "o23", customerId: "c8",  productId: "1",  productName: "やさしい料理の基本",      amount: 1200,  status: "completed",        orderedAt: "2026-02-20" },
  { id: "o24", customerId: "c8",  productId: "11", productName: "ふわふわパンケーキの科学", amount: 1100,  status: "completed",        orderedAt: "2026-03-19" },
  { id: "o25", customerId: "c8",  productId: "7",  productName: "鮭の作り置きレシピ",      amount: 980,   status: "refunded",         orderedAt: "2026-04-05" },
  { id: "o26", customerId: "c9",  productId: "5",  productName: "献立テンプレ30日分",      amount: 1500,  status: "completed",        orderedAt: "2026-04-01" },
  { id: "o27", customerId: "c10", productId: "8",  productName: "パスタの基礎 動画講座",   amount: 6800,  status: "completed",        orderedAt: "2026-03-01" },
  { id: "o28", customerId: "c10", productId: "4",  productName: "朝食レシピ30",           amount: 800,   status: "completed",        orderedAt: "2026-04-14" },
  { id: "o29", customerId: "c10", productId: "1",  productName: "やさしい料理の基本",      amount: 1200,  status: "processing",       orderedAt: "2026-06-10" },
  { id: "o30", customerId: "c11", productId: "9",  productName: "サラダの教科書",         amount: 800,   status: "completed",        orderedAt: "2026-05-02" },
  { id: "o31", customerId: "c12", productId: "4",  productName: "朝食レシピ30",           amount: 800,   status: "completed",        orderedAt: "2026-05-20" },
  { id: "o32", customerId: "c12", productId: "1",  productName: "やさしい料理の基本",      amount: 1200,  status: "completed",        orderedAt: "2026-06-15" },
];

export const SUBSCRIPTIONS: Subscription[] = [
  { id: "s1", customerId: "c3",  planName: "月額プラン",   amount: 1980, nextBillingDate: "2026-07-08",  status: "active" },
  { id: "s2", customerId: "c5",  planName: "月額プラン",   amount: 1980, nextBillingDate: "2026-07-10",  status: "active" },
  { id: "s3", customerId: "c8",  planName: "プレミアムプラン", amount: 3980, nextBillingDate: "2026-07-19",  status: "active" },
  { id: "s4", customerId: "c10", planName: "月額プラン",   amount: 1980, nextBillingDate: "2026-07-14",  status: "active" },
];
