import type { IncomeEntry } from "./types";

// TODO: 実 API 接続時にこのモックデータを削除し、API レスポンスに差し替える
export const INCOME_ENTRIES: IncomeEntry[] = [
  { id: "o1",  orderedAt: "2026-03-10", customerId: "c1",  customerName: "田中 太郎",  productId: "9",  productName: "サラダの教科書",             amount: 1400,  status: "completed" },
  { id: "o2",  orderedAt: "2026-04-22", customerId: "c1",  customerName: "田中 太郎",  productId: "4",  productName: "朝食レシピ30",               amount: 800,   status: "completed" },
  { id: "o3",  orderedAt: "2026-05-01", customerId: "c1",  customerName: "田中 太郎",  productId: "6",  productName: "だしの基本ガイドブック",       amount: 3000,  status: "refunded" },
  { id: "o4",  orderedAt: "2026-01-15", customerId: "c2",  customerName: "佐藤 花子",  productId: "1",  productName: "やさしい料理の基本",           amount: 1200,  status: "completed" },
  { id: "o5",  orderedAt: "2025-12-01", customerId: "c3",  customerName: "鈴木 一郎",  productId: "8",  productName: "パスタの基礎 動画講座",         amount: 6800,  status: "completed" },
  { id: "o6",  orderedAt: "2026-01-05", customerId: "c3",  customerName: "鈴木 一郎",  productId: "2",  productName: "旬の野菜 動画レッスン全30本", amount: 9800,  status: "completed" },
  { id: "o7",  orderedAt: "2026-02-14", customerId: "c3",  customerName: "鈴木 一郎",  productId: "9",  productName: "サラダの教科書",             amount: 1400,  status: "completed" },
  { id: "o8",  orderedAt: "2026-03-20", customerId: "c3",  customerName: "鈴木 一郎",  productId: "4",  productName: "朝食レシピ30",               amount: 800,   status: "completed" },
  { id: "o9",  orderedAt: "2026-05-10", customerId: "c3",  customerName: "鈴木 一郎",  productId: "11", productName: "ふわふわパンケーキの科学",     amount: 1100,  status: "completed" },
  { id: "o10", orderedAt: "2026-02-01", customerId: "c4",  customerName: "山田 美咲",  productId: "5",  productName: "献立テンプレ30日分",           amount: 1500,  status: "completed" },
  { id: "o11", orderedAt: "2026-06-20", customerId: "c4",  customerName: "山田 美咲",  productId: "7",  productName: "鮭の作り置きレシピ",           amount: 980,   status: "awaiting_payment" },
  { id: "o12", orderedAt: "2025-11-20", customerId: "c5",  customerName: "中村 健太",  productId: "8",  productName: "パスタの基礎 動画講座",         amount: 6800,  status: "completed" },
  { id: "o13", orderedAt: "2025-12-15", customerId: "c5",  customerName: "中村 健太",  productId: "2",  productName: "旬の野菜 動画レッスン全30本", amount: 9800,  status: "completed" },
  { id: "o14", orderedAt: "2026-01-08", customerId: "c5",  customerName: "中村 健太",  productId: "9",  productName: "サラダの教科書",             amount: 1400,  status: "completed" },
  { id: "o15", orderedAt: "2026-02-10", customerId: "c5",  customerName: "中村 健太",  productId: "4",  productName: "朝食レシピ30",               amount: 800,   status: "refunded" },
  { id: "o16", orderedAt: "2026-03-05", customerId: "c6",  customerName: "伊藤 さくら", productId: "1",  productName: "やさしい料理の基本",           amount: 980,   status: "completed" },
  { id: "o17", orderedAt: "2026-04-10", customerId: "c7",  customerName: "渡辺 大輔",  productId: "5",  productName: "献立テンプレ30日分",           amount: 1500,  status: "completed" },
  { id: "o18", orderedAt: "2026-05-15", customerId: "c7",  customerName: "渡辺 大輔",  productId: "7",  productName: "鮭の作り置きレシピ",           amount: 980,   status: "completed" },
  { id: "o19", orderedAt: "2025-10-01", customerId: "c8",  customerName: "小林 あかり", productId: "8",  productName: "パスタの基礎 動画講座",         amount: 6800,  status: "completed" },
  { id: "o20", orderedAt: "2025-11-10", customerId: "c8",  customerName: "小林 あかり", productId: "2",  productName: "旬の野菜 動画レッスン全30本", amount: 9800,  status: "completed" },
  { id: "o21", orderedAt: "2025-12-20", customerId: "c8",  customerName: "小林 あかり", productId: "9",  productName: "サラダの教科書",             amount: 1400,  status: "completed" },
  { id: "o22", orderedAt: "2026-01-15", customerId: "c8",  customerName: "小林 あかり", productId: "4",  productName: "朝食レシピ30",               amount: 800,   status: "completed" },
  { id: "o23", orderedAt: "2026-02-20", customerId: "c8",  customerName: "小林 あかり", productId: "1",  productName: "やさしい料理の基本",           amount: 1200,  status: "completed" },
  { id: "o24", orderedAt: "2026-03-19", customerId: "c8",  customerName: "小林 あかり", productId: "11", productName: "ふわふわパンケーキの科学",     amount: 1100,  status: "completed" },
  { id: "o25", orderedAt: "2026-04-05", customerId: "c8",  customerName: "小林 あかり", productId: "7",  productName: "鮭の作り置きレシピ",           amount: 980,   status: "refunded" },
  { id: "o26", orderedAt: "2026-04-01", customerId: "c9",  customerName: "加藤 浩二",  productId: "5",  productName: "献立テンプレ30日分",           amount: 1500,  status: "completed" },
  { id: "o27", orderedAt: "2026-03-01", customerId: "c10", customerName: "吉田 真由",  productId: "8",  productName: "パスタの基礎 動画講座",         amount: 6800,  status: "completed" },
  { id: "o28", orderedAt: "2026-04-14", customerId: "c10", customerName: "吉田 真由",  productId: "4",  productName: "朝食レシピ30",               amount: 800,   status: "completed" },
  { id: "o29", orderedAt: "2026-06-10", customerId: "c10", customerName: "吉田 真由",  productId: "1",  productName: "やさしい料理の基本",           amount: 1200,  status: "processing" },
  { id: "o30", orderedAt: "2026-05-02", customerId: "c11", customerName: "松本 翔",    productId: "9",  productName: "サラダの教科書",             amount: 800,   status: "completed" },
  { id: "o31", orderedAt: "2026-05-20", customerId: "c12", customerName: "井上 奈々",  productId: "4",  productName: "朝食レシピ30",               amount: 800,   status: "completed" },
  { id: "o32", orderedAt: "2026-06-15", customerId: "c12", customerName: "井上 奈々",  productId: "1",  productName: "やさしい料理の基本",           amount: 1200,  status: "completed" },
];
